spring:
  application:
    name: chathub-api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
  datasource:
    hikari:
      connectionTestQuery: select 1;
      maximumPoolSize: 10
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost/todos
    username: postgres
    password: postgres
  cache.cache-names: todos
  cache.caffeine.spec: maximumSize=500,expireAfterAccess=600s

server:
  compression.enabled: true
  port: 8080