spring:
  application:
    name: chathub-api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:test;MODE=PostgreSQL
  h2.console.enabled: true
  cache.cache-names: todos
  cache.caffeine.spec: maximumSize=500,expireAfterAccess=600s

server:
  compression.enabled: true
  port: 8080