spring:
  application:
    name: chathub-api
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
  datasource:
    platform: h2
    url: jdbc:h2:mem:test;MODE=PostgreSQL
  h2.console.enabled: true

server:
  compression.enabled: true
  port: 8080